'use client';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BookOpen, Plus, Search, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Skeleton } from '@/components/ui/skeleton';
import { toast } from '@/hooks/use-toast'; import { questionsService, type QuestionInput } from '@/services/questions.service'; import { Difficulty } from '@intvwplt/shared';
const empty: QuestionInput = { category: '', technology: '', question: '', expectedAnswer: '', difficulty: Difficulty.MEDIUM, tags: [] };
export default function QuestionBankPage() {
 const qc=useQueryClient(),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState(empty);
 const q=useQuery({queryKey:['questions',search,category],queryFn:()=>questionsService.list({search:search||undefined,category:category||undefined})}); const cats=useQuery({queryKey:['question-categories'],queryFn:questionsService.categories}); const refresh=()=>{qc.invalidateQueries({queryKey:['questions']});qc.invalidateQueries({queryKey:['question-categories']})};
 const create=useMutation({mutationFn:()=>questionsService.create(form),onSuccess:()=>{setForm(empty);setOpen(false);refresh();toast({title:'Question added'})},onError:()=>toast({title:'Could not add question',variant:'destructive'})}); const remove=useMutation({mutationFn:questionsService.remove,onSuccess:refresh});
 return <div className="space-y-6 pb-12"><div className="flex justify-between"><div><h1 className="flex gap-2 text-2xl font-bold text-sunset-cream"><BookOpen className="text-sunset-orange"/>Question Bank</h1><p className="text-sm text-stone-400">Reusable technical interview questions and rubrics.</p></div><Button onClick={()=>setOpen(!open)} className="gradient-sunset-btn"><Plus className="mr-1 h-4 w-4"/>Add question</Button></div>
 {open&&<form onSubmit={e=>{e.preventDefault();create.mutate()}} className="space-y-3 rounded-xl border border-[#36271D] bg-[#18110C] p-5"><div className="grid gap-3 sm:grid-cols-2"><Input required placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><Input placeholder="Technology" value={form.technology??''} onChange={e=>setForm({...form,technology:e.target.value})}/></div><textarea required minLength={5} value={form.question} placeholder="Question" onChange={e=>setForm({...form,question:e.target.value})} className="min-h-24 w-full rounded border border-[#36271D] bg-[#120B07] p-3 text-sunset-cream"/><textarea value={form.expectedAnswer??''} placeholder="Expected answer / rubric" onChange={e=>setForm({...form,expectedAnswer:e.target.value})} className="min-h-20 w-full rounded border border-[#36271D] bg-[#120B07] p-3 text-sunset-cream"/><div className="flex gap-3"><select value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value as Difficulty})} className="rounded bg-[#120B07] p-2 text-sunset-cream">{Object.values(Difficulty).map(x=><option key={x}>{x}</option>)}</select><Input placeholder="Tags, comma separated" onChange={e=>setForm({...form,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/><Button type="submit">Save</Button></div></form>}
 <div className="flex gap-3 rounded-xl border border-[#36271D] bg-[#18110C] p-4"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-stone-500"/><Input className="pl-9" placeholder="Search questions" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded bg-[#120B07] p-2 text-sunset-cream"><option value="">All categories</option>{cats.data?.map(x=><option key={x}>{x}</option>)}</select></div>
 {q.isLoading?<Skeleton className="h-48"/>:<div className="grid gap-4 md:grid-cols-2">{q.data?.map(x=><article key={x.id} className="rounded-xl border border-[#36271D] bg-[#18110C] p-5"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase text-sunset-orange">{x.category}{x.technology&&` · ${x.technology}`}</p><h2 className="mt-1 font-semibold text-sunset-cream">{x.question}</h2></div><Button variant="ghost" size="icon" onClick={()=>remove.mutate(x.id)}><Trash2 className="h-4 w-4"/></Button></div><p className="mt-3 text-xs text-stone-400">{x.difficulty}{x.expectedAnswer&&` · Rubric: ${x.expectedAnswer}`}</p></article>)}</div>}</div>;
}
