export enum UserRole {
  ADMIN = 'ADMIN',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  RECRUITER = 'RECRUITER',
  INTERVIEWER = 'INTERVIEWER',
}

export enum CandidateStatus {
  NEW = 'NEW',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  INTERVIEWING = 'INTERVIEWING',
  NEXT_ROUND = 'NEXT_ROUND',
  ON_HOLD = 'ON_HOLD',
  REJECTED = 'REJECTED',
  HIRED = 'HIRED',
}

export enum InterviewStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum Recommendation {
  STRONG_HIRE = 'STRONG_HIRE',
  HIRE = 'HIRE',
  NEXT_ROUND = 'NEXT_ROUND',
  HOLD = 'HOLD',
  REJECT = 'REJECT',
}

export enum Difficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
}

export enum AvailabilityExceptionType {
  UNAVAILABLE = 'UNAVAILABLE',
  AVAILABLE = 'AVAILABLE',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}

export enum QuestionCategory {
  JAVASCRIPT = 'JavaScript',
  REACT = 'React',
  NODEJS = 'Node.js',
  EXPRESS = 'Express',
  POSTGRESQL = 'PostgreSQL',
  MONGODB = 'MongoDB',
  AWS = 'AWS',
  SYSTEM_DESIGN = 'System Design',
  DSA = 'DSA',
  GENERAL_BACKEND = 'General Backend',
  BEHAVIORAL = 'Behavioral',
  JAVA = 'Java',
  SPRING_BOOT = 'Spring Boot',
  TYPESCRIPT = 'TypeScript',
  DOCKER = 'Docker',
  KUBERNETES = 'Kubernetes',
}

export enum AuditAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  CANDIDATE_CREATED = 'CANDIDATE_CREATED',
  CANDIDATE_UPDATED = 'CANDIDATE_UPDATED',
  CANDIDATE_DELETED = 'CANDIDATE_DELETED',
  RESUME_UPLOADED = 'RESUME_UPLOADED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  INTERVIEW_RESCHEDULED = 'INTERVIEW_RESCHEDULED',
  INTERVIEW_CANCELLED = 'INTERVIEW_CANCELLED',
  INTERVIEW_STARTED = 'INTERVIEW_STARTED',
  INTERVIEW_COMPLETED = 'INTERVIEW_COMPLETED',
  FEEDBACK_SUBMITTED = 'FEEDBACK_SUBMITTED',
  CANDIDATE_REJECTED = 'CANDIDATE_REJECTED',
  CANDIDATE_NEXT_ROUND = 'CANDIDATE_NEXT_ROUND',
  CANDIDATE_HIRED = 'CANDIDATE_HIRED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  REFRESH_TOKEN_REVOKED = 'REFRESH_TOKEN_REVOKED',
}
