'use client';
import { useEffect, useRef, useState } from 'react';
import { useParams } from 'next/navigation';
import { useMutation, useQuery } from '@tanstack/react-query';
import { io, type Socket } from 'socket.io-client';
import { Mic, MicOff, Video, VideoOff, PhoneOff } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { interviewsService } from '@/services/interviews.service';
import { feedbackService } from '@/services/feedback.service';
import { useAuthStore } from '@/stores/auth.store';
import { Recommendation, type InterviewDto, type InterviewQuestionDto } from '@intvwplt/shared';
const baseUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000';
export default function InterviewRoomPage() {
  const { meetingRoomId } = useParams<{ meetingRoomId: string }>(); const token = useAuthStore((s) => s.accessToken);
  const localVideo = useRef<HTMLVideoElement>(null); const remoteVideo = useRef<HTMLVideoElement>(null); const peer = useRef<RTCPeerConnection | null>(null); const socket = useRef<Socket | null>(null);
  const [mic, setMic] = useState(true); const [camera, setCamera] = useState(true); const [notes, setNotes] = useState(''); const [scores, setScores] = useState<Record<string, number>>({}); const [recommendation, setRecommendation] = useState(Recommendation.HOLD);
  const room = useQuery({ queryKey: ['interview-room', meetingRoomId], queryFn: async () => { const result = await interviewsService.list({ limit: 100 }); return result.items.find((item: InterviewDto) => item.meetingRoomId === meetingRoomId); } });
  const interview = room.data; const saveNotes = useMutation({ mutationFn: () => interviewsService.updateNotes(interview!.id, { notes }) }); const submit = useMutation({ mutationFn: () => feedbackService.submit(interview!.id, { scores, recommendation }) });
  useEffect(() => { if (!token || !meetingRoomId) return; let stream: MediaStream | undefined; const start = async () => { stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); if (localVideo.current) localVideo.current.srcObject = stream; peer.current = new RTCPeerConnection({ iceServers: [{ urls: 'stun:stun.l.google.com:19302' }] }); stream.getTracks().forEach((track) => peer.current!.addTrack(track, stream!)); peer.current.ontrack = (event) => { if (remoteVideo.current) remoteVideo.current.srcObject = event.streams[0]; }; socket.current = io(baseUrl, { auth: { token } }); socket.current.emit('join-interview', { meetingRoomId }); }; start().catch(console.error); return () => { stream?.getTracks().forEach((track) => track.stop()); peer.current?.close(); socket.current?.disconnect(); }; }, [meetingRoomId, token]);
  if (!interview) return <div className="p-8 text-stone-400">Loading interview room…</div>;
  const toggle = (kind: 'audio' | 'video', value: boolean, set: (value: boolean) => void) => { const stream = localVideo.current?.srcObject as MediaStream | null; stream?.getTracks().filter((track) => track.kind === kind).forEach((track) => { track.enabled = !value; }); set(!value); };
  return <div className="grid gap-5 xl:grid-cols-[1fr_360px]"><main className="space-y-4"><div className="rounded-xl border border-[#36271D] bg-[#18110C] p-4"><h1 className="font-bold text-sunset-cream">{interview.candidate.firstName} {interview.candidate.lastName}</h1><p className="text-xs text-stone-400">{interview.interviewType.name}</p></div><div className="grid gap-4 md:grid-cols-2"><video ref={localVideo} autoPlay muted playsInline className="aspect-video rounded-xl bg-black" /><video ref={remoteVideo} autoPlay playsInline className="aspect-video rounded-xl bg-black" /></div><div className="flex justify-center gap-3"><Button variant="outline" onClick={() => toggle('audio', mic, setMic)}>{mic ? <Mic /> : <MicOff />}</Button><Button variant="outline" onClick={() => toggle('video', camera, setCamera)}>{camera ? <Video /> : <VideoOff />}</Button><Button variant="destructive" onClick={() => history.back()}><PhoneOff /></Button></div></main><aside className="space-y-4"><section className="rounded-xl border border-[#36271D] bg-[#18110C] p-4"><h2 className="font-semibold text-sunset-cream">Notes</h2><textarea value={notes} onChange={(event) => setNotes(event.target.value)} className="mt-2 min-h-36 w-full rounded bg-[#120B07] p-2 text-sm text-sunset-cream"/><Button className="mt-2" onClick={() => saveNotes.mutate()}>Save notes</Button></section><section className="rounded-xl border border-[#36271D] bg-[#18110C] p-4"><h2 className="font-semibold text-sunset-cream">Scorecard</h2>{interview.questions?.map((question: InterviewQuestionDto) => <label key={question.id} className="mt-3 block text-xs text-stone-300">{question.questionText}<input type="number" min="1" max="5" onChange={(event) => setScores({ ...scores, [question.id]: Number(event.target.value) })} className="mt-1 block w-16 rounded bg-[#120B07] p-1" /></label>)}<select value={recommendation} onChange={(event) => setRecommendation(event.target.value as Recommendation)} className="mt-3 w-full rounded bg-[#120B07] p-2">{Object.values(Recommendation).map((value) => <option key={value}>{value}</option>)}</select><Button className="mt-3" onClick={() => submit.mutate()}>Submit scorecard</Button></section></aside></div>;
}
